### PR TITLE
Need explicit require for symbols

### PR DESCRIPTION
**Pull request by repeatedly**

### CODE REVIEW

**Comment by sonots** [comment]
From what version do we need this, v0.14?

**Comment by sonots** [comment]
I thought, before, fluentd did "require" most of everything, then require plugins.

**Comment by sonots** [comment]
Let me know if I was missing something

**Comment by repeatedly** [comment]
v0.14 and recent v0.12.

**Comment by repeatedly** [comment]
ping?

**Comment by sonots** [comment]
Thanks

**Comment by repeatedly** [comment]
Could you merge and release new version?

**Comment by sonots** [comment]
0.0.3 is released

**Pull request merged**
